export const GET_PROJECTS = 'GET_PROJECTS';
export const REGISTER_PROJECT = 'REGISTER_PROJECT';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const GET_TASKS = 'GET_TASKS';
export const REGISTER_TASK = 'REGISTER_TASK';
